export const urls = {
  HOME: '/',
  SHOP: "/shop",
  ABOUT: '/about',
  CHECKOUT: '/checkout',
  FAQ: '/faq',
  CONTACT: '/contact',
  BLOG: '/blog',
  PRODUCTS: '/products',
  DASHBOARD: '/dashboard',
  ADD_PRODUCT: '/add-product',
  EDIT_PRODUCT: '/edit-product/:id',
  BASKET: '/basket',
  WISHLIST: '/wishlist',
  PRODUCT_DETAILS: '/product/:id',
  LOGIN: '/login',
  REGISTER: '/register',
  ACCOUNT: '/account',
};
